Repository BinaryBitBytes/AirWorthy, pull requests merged in 2022-06, with the labels that each got.

#45 Create MIT Lisence
  LICENSE
Labels: documentation

#50 New tree
  .gitignore
  client/package-lock.json
  client/src/components/Footer.js
  client/src/components/Navbar.js
  client/src/components/intro.js
  package-lock.json
  server/package-lock.json
Labels: bug, Hotfix

#61 Routes
  .gitignore
  client/src/Utils/api.js
  server/config/connection.js
  server/controllers/Ariliner-controller.js
  server/controllers/Inspector-controller.js
  server/controllers/Manager-controller.js
  server/controllers/Project-controller.js
  server/controllers/Technician-controller.js
  server/controllers/user-controller.js
  server/server.js
Labels: enhancement

#63 Matchup controllers
  server/models/Airliner.js
  server/models/Inspector.js
  server/models/Manager.js
  server/models/Technician.js
  server/schemas/resolvers.js
Labels: enhancement, Hotfix

#65 updated mongoose.connect DB name
  server/config/connection.js
Labels: Hotfix

#69 changed api route on form.js from manger to project api and minor cha…
  client/src/components/manager/Form.js
  client/src/components/stars.scss
Labels: enhancement

#76 updated index.js in models by wrapping these const as objects with { }
  server/models/index.js
Labels: bug, Hotfix

#80 updated server/ with routes/api
  server/routes/api/index.js
  server/routes/api/manager-routes.js
  server/routes/api/technician-routes.js
  server/routes/index.js
  server/server.js
Labels: bug, enhancement, Hotfix

#81 updated index.js
  server/routes/api/index.js
Labels: bug, Hotfix

#90 please help us
  server/routes/api/index.js
Labels: bug, Hotfix

#98 hardcoded seeds with .json values
  server/schemas/resolvers.js
  server/seeds/airlinerData.json
  server/seeds/inspectorData.json
  server/seeds/managerData.json
  server/seeds/projectData.json
  server/seeds/seed.js
  server/seeds/technicianData.json
Labels: bug, enhancement, Hotfix, HARD CODED
